%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Program Files\National Instruments\LabVIEW 2017\user.lib\CONEX\Data.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/27 12:50:51

%% Initialize variables.
filename = 'C:\Program Files\National Instruments\LabVIEW 2017\user.lib\CONEX\Data.log';
delimiter = ' ';

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

% Converts strings in the input cell array to numbers. Replaced non-numeric
% strings with NaN.
rawData = dataArray{7};
for row=1:size(rawData, 1);
    % Create a regular expression to detect and remove non-numeric prefixes and
    % suffixes.
    regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
    try
        result = regexp(rawData{row}, regexstr, 'names');
        numbers = result.numbers;
        
        % Detected commas in non-thousand locations.
        invalidThousandsSeparator = false;
        if any(numbers==',');
            thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
            if isempty(regexp(numbers, thousandsRegExp, 'once'));
                numbers = NaN;
                invalidThousandsSeparator = true;
            end
        end
        % Convert numeric strings to numbers.
        if ~invalidThousandsSeparator;
            numbers = textscan(strrep(numbers, ',', ''), '%f');
            numericData(row, 7) = numbers{1};
            raw{row, 7} = numbers{1};
        end
    catch me
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, 7);
rawCellColumns = raw(:, [1,2,3,4,5,6]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
ConData = raw;
%% Clear temporary variables
clearvars delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;



%% ANALYSIS

% Before we start, Matlab shitty import has a SUPERFUCKINANNOYING feature
% where it imports differently if you use the automated script rather than
% their GUI. It turns the COM column into a mix of 'char' and 'doubles'
% which makes it super hard to manipulate. This wasted like and hour and
% a half of my damn time trying to figure out why they weren't indexing
% right. 
for i = 1:size(ConData,1)
    if strcmp(ConData(i,end),'')
        ConData{i,end} = NaN;
    end
end

% Also get timestamp for Log file.
D = dir(filename);
DateTag = D.date;
DateTag(strfind(DateTag,' '))='_';
DateTag(strfind(DateTag,':'))='-';
% Get timestamps and sort data from text file and use it to calculate metrics like time gap
% between actuator queries.
% Three actuators with these COM numbers (note, different labeling than
% Windows COMs). Find the three COM numbers.
COMnums = sort(unique([ConData{~isnan([ConData{:,end}]),end}]));

% Do calculations for each COM
for i = 1:length(COMnums)
    close all;
    h = figure('position',[100 100 1000 400]);
    % Find the rows corresponding to the three COM ports. 
    COMs = ConData(:,end);
    ind = [];
    ind = find([ConData{:,end}]==COMnums(i));
    % For each COM, take that row and the row above it.
    ind = sort([ind (ind-1)]);

    dat = ConData(ind,:);
    
    % Omit 'R: rows, which stand for 'response' (I think)
    Rs = find(strcmp(dat(:,2),'R:')); Rs = sort([Rs; (Rs+1)]);
    dat(Rs,:) = [];
    
    % Plot time gaps between consecutive Queries ('Q:' rows (I think))
    t = datenum(dat(2:2:end,4));
    
    t = (t-t(1))*86400;
    
    d = diff(t*1000);
    
    ran = 1:(length(t)-1)'; %50;
    
    subplot(1,2,1)
    plot(t(ran),'.-');
    xlabel('Array element'); ylabel('time (s)');
    subplot(1,2,2)
    plot(d(ran));
    xlabel('Array element'); ylabel('lag between Q''s (ms)');
    0;
    
    saveas(gcf,[UpOneDir(filename) 'TimeLags_' DateTag 'COM' num2str(COMnums(i)) '.fig'])
end

copyfile(filename,[filename(1:end-4) '_TimeLags_' DateTag filename(end-3:end)])

