function [O2T, O2] = O2FromDecayTau(RuthPreCalPath,DropRng,RestRng,O2Cons,OmitFrames)
% O2 experiments performed by equilibrating to an O2 start concentration
% (typically 1%) while monitoring fluorescence of a ruthenium droplet in
% the same chamber under oil. This time series can be fit to find the O2
% exponential exchange decay time. 
% This DecTau can then be used with the step change timings of O2 drops.
% E.g. step-drop from 1% to 0% O2 at 13:23:05. The equilibration to 0% will
% be an exponential decay with time constant DecTau, so we can extract O2
% vs time.

% Restore: O2 typically restored to original concentration at a later time.
% Include this info.

% Inputs:
% -RuthPreCalPath: Path to Ruthenium pre-experiment equilibration Ints. 
%     NOTE: TotalIntensities.mat file generated by 'IntensitymatrixTiffs.m'
% -DropRng: O2 drop start finish times. [t0 t1] -> DateString formats
% -RestRng: O2 restore start finish times. [t0' t1']
% -O2Cons: Initial O2 concentration and drop concentration. [O2_i O2_f]

% NOTE: all times in absolute time units

% clear all
% RuthPreCalPath = 'C:\Users\Tim\Documents\Academic - Research\Data\2016-10-12 Emily O2 chamber tests\Chamber1_900uLOil_a1_20to5O2';
% DropRng = {'2016-2-10 17:20:00' '2016-2-10 18:37:00'};
% RestRng = {'2016-2-10 18:37:00' '2016-2-10 19:28:00'};
% O2Cons = [1 0];

% timeunit = 3600; % 60 gives minutes, 3600 for hours, 86400 for days
% switch timeunit
%     case 1;
%         tlab = 'Time (s)';
%     case 60;
%         tlab = 'Time (min)';
%     case 3600;
%         tlab = 'Time (h)';
%     case 86400;
%         tlab = 'Time (days)';
% end

% Versions:



%% Load Ruth series and convert times to datenum
load([RuthPreCalPath '\TotalIntensities.mat']);
% If Drop and Restore times are not specified, assume drop started at
% beginning of experiment and lasted until end. Get start and stop times
% from the timestamps of the first and last .std files in the folder
D = dir([RuthPreCalPath '\*.sdt']);
if exist('DropRng')&iscell(DropRng)
    DropRng = datenum(DropRng)+1/24/60;
    % Add a minute to everything because it takes about a minute to flush the
    % chamber with gas.
else
    DropRng = [datenum(D(1).date) datenum(D(end).date)];
    DropRng = DropRng+1/24/60;
end
% And if not specified, assume no restore occurs. Set st/end both to end 
if exist('RestRng')&iscell(RestRng)
    RestRng = datenum(RestRng)+1/24/60;
else
    RestRng = [datenum(D(end).date) datenum(D(end).date)];
    RestRng = RestRng+1/24/60;
end
if ~exist('OmitFrames') OmitFrames = []; end
% Truncate OmitFrames indexes if they are larger than the number of frames
if max(OmitFrames)>length(sdtendtimes) 
    CutFrs = find(OmitFrames>length(sdtendtimes));
    OmitFrames(CutFrs)= []; 
end


%% Extract DecTau from Ruth series
ts = (sdtendtimes-sdtendtimes(1))*24; % Get decay time in units of hours
RuthIrrs = -TotalInts;
% Fits - shift curves to start at t=0
ts(OmitFrames)=[];RuthIrrs(OmitFrames)=[];
RuthIrrs = RuthIrrs - min(RuthIrrs);
[fitresult, gof] = ExpFitO2(ts, RuthIrrs); 
coeffs = coeffvalues(fitresult);
DecTau = coeffs(2); % Decay Tau in units of hours here.

% Get O2 values for O2 drop range
DropFitT = 0:.005:(DropRng(2)-DropRng(1))*24;
DropFit = (O2Cons(1)-O2Cons(2))*exp(-DropFitT./DecTau)+O2Cons(2);
DropFitT = (DropFitT)/24+DropRng(1); % Back to datenum units

% Get O2 values for O2 restore range
RestFitT = 0:.005:(RestRng(2)-RestRng(1))*24;
RestFit = O2Cons(1)-(O2Cons(1)-O2Cons(2))*exp(-RestFitT./DecTau);
RestFitT = (RestFitT)/24+RestRng(1); % Back to datenum units

%% Stitch full O2 vs exp time (relative to 1st frame save time), and save
O2T = [DropFitT'; RestFitT'];
O2 = [DropFit'; RestFit'];

save([RuthPreCalPath '\O2Info.mat'],'O2T','O2','DropRng','RestRng','O2Cons','DecTau')
set(gcf,'paperPositionmode','auto')
saveas(gcf,[RuthPreCalPath '\RuthFit.jpg'])
saveas(gcf,[RuthPreCalPath '\RuthFit.fig'])

%% Plot O2 vs time and save
figure('position',[800 200 500 350]);
% figure('units','normalized','position',[.1 .1 .35 .3]);
plot((O2T-O2T(1))*24,O2);
set(gca,'fontsize',10)
xlabel('time (h)','fontsize',12);ylabel('O2 conc (%)','fontsize',12);
set(gcf,'paperPositionmode','auto')
saveas(gcf,[RuthPreCalPath '\O2VsT_vals.jpg'])
saveas(gcf,[RuthPreCalPath '\O2VsT_vals.fig'])

